name: Build and Export (rpi3-armv8)

on: workflow_dispatch

jobs:
  build-and-export:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build process
        run:  ./build.sh rpi3-armv8 --export
      - name: archive syroot
        run:  |
          sysroot=$(echo sysroot-*)
          tar cf $sysroot.tar $sysroot
      - name: archive x-tools
        run:  |
          tar cf x-tools.tar x-tools
      - name: export staging
        uses: actions/upload-artifact@v3
        with:
          name: staging-rpi3-armv8
          path: staging*.tar
      - name: export sysroot
        uses: actions/upload-artifact@v3
        with:
          name: sysroot-rpi3-armv8
          path: sysroot*.tar
      - name: export cross-tools
        uses: actions/upload-artifact@v3
        with:
          name: x-tools-rpi3-armv8
          path: x-tools.tar
    
